2017-04-16 19:04:48,515: umgr.scheduling.2.child: umgr.scheduling.2               : MainThread     : ERROR   : unit schedule preparation failed
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/umgr/scheduler/round_robin.py", line 131, in _schedule_units
    unit['sandbox'] = self._session._get_unit_sandbox(unit, pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 846, in _get_unit_sandbox
    pilot_sandbox = self._get_pilot_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 831, in _get_pilot_sandbox
    session_sandbox = self._get_session_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 809, in _get_session_sandbox
    global_sandbox  = self._get_global_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 774, in _get_global_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
AuthorizationFailed: read from process failed '[Errno 5] Input/output error' : (the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
) ((To access the system:

1) If not using ssh-keys, please enter your TACC password at the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
)) (/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +49 (translate_exception)  :  e = se.AuthorizationFailed (cmsg))
2017-04-16 19:04:59,730: umgr.scheduling.2.child: umgr.scheduling.2               : MainThread     : ERROR   : unit schedule preparation failed
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/umgr/scheduler/round_robin.py", line 131, in _schedule_units
    unit['sandbox'] = self._session._get_unit_sandbox(unit, pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 846, in _get_unit_sandbox
    pilot_sandbox = self._get_pilot_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 831, in _get_pilot_sandbox
    session_sandbox = self._get_session_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 809, in _get_session_sandbox
    global_sandbox  = self._get_global_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 774, in _get_global_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
AuthorizationFailed: read from process failed '[Errno 5] Input/output error' : (the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
) ((To access the system:

1) If not using ssh-keys, please enter your TACC password at the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
)) (/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +49 (translate_exception)  :  e = se.AuthorizationFailed (cmsg))
2017-04-16 19:05:09,952: umgr.scheduling.2.child: umgr.scheduling.2               : MainThread     : ERROR   : unit schedule preparation failed
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/umgr/scheduler/round_robin.py", line 131, in _schedule_units
    unit['sandbox'] = self._session._get_unit_sandbox(unit, pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 846, in _get_unit_sandbox
    pilot_sandbox = self._get_pilot_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 831, in _get_pilot_sandbox
    session_sandbox = self._get_session_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 809, in _get_session_sandbox
    global_sandbox  = self._get_global_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 774, in _get_global_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
AuthorizationFailed: read from process failed '[Errno 5] Input/output error' : (the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
) ((To access the system:

1) If not using ssh-keys, please enter your TACC password at the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
)) (/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +49 (translate_exception)  :  e = se.AuthorizationFailed (cmsg))
2017-04-16 19:05:20,161: umgr.scheduling.2.child: umgr.scheduling.2               : MainThread     : ERROR   : unit schedule preparation failed
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/umgr/scheduler/round_robin.py", line 131, in _schedule_units
    unit['sandbox'] = self._session._get_unit_sandbox(unit, pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 846, in _get_unit_sandbox
    pilot_sandbox = self._get_pilot_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 831, in _get_pilot_sandbox
    session_sandbox = self._get_session_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 809, in _get_session_sandbox
    global_sandbox  = self._get_global_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 774, in _get_global_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
AuthorizationFailed: read from process failed '[Errno 5] Input/output error' : (the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
) ((To access the system:

1) If not using ssh-keys, please enter your TACC password at the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
)) (/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +49 (translate_exception)  :  e = se.AuthorizationFailed (cmsg))
2017-04-16 19:05:30,370: umgr.scheduling.2.child: umgr.scheduling.2               : MainThread     : ERROR   : unit schedule preparation failed
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/umgr/scheduler/round_robin.py", line 131, in _schedule_units
    unit['sandbox'] = self._session._get_unit_sandbox(unit, pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 846, in _get_unit_sandbox
    pilot_sandbox = self._get_pilot_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 831, in _get_pilot_sandbox
    session_sandbox = self._get_session_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 809, in _get_session_sandbox
    global_sandbox  = self._get_global_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 774, in _get_global_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
AuthorizationFailed: read from process failed '[Errno 5] Input/output error' : (the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
) ((To access the system:

1) If not using ssh-keys, please enter your TACC password at the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
)) (/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +49 (translate_exception)  :  e = se.AuthorizationFailed (cmsg))
2017-04-16 19:55:25,207: umgr.scheduling.2.child: umgr.scheduling.2               : MainThread     : ERROR   : TERM : umgr.scheduling.2.child run intr
2017-04-16 19:55:25,211: umgr.scheduling.2.child: umgr.scheduling.2               : MainThread     : ERROR   : TERM : umgr.scheduling.2.child run final
